################################################################################################
# Requirements & Config.
################################################################################################


#-----------------------------------------------
# Build Settings
#-----------------------------------------------
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']

#-----------------------------------------------
# Plugins
#-----------------------------------------------
plugins_dir:
- jekyll-sitemap

safe: false

################################################################################################
# Site Settings
################################################################################################
title: "BSidesNYC"
email: "bsides@bsidesnyc.org"
twitterAccount: "@bsidesnyc"
description: "BSides NYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community, and we truly strive to keep information free."
url: "https://bsidesnyc.org" #https://bsidesnyc.github.io
timezone: "America/New_York"
conYear: "2024"
previousSponsorCount: "22"
previousAttendeeCount: "1000"
logoImage: "/about/logo_white.png"
checkinMessage: "General attendee check-in opens at 8:30am ET. Speakers, sponsors, villages, CTF organizers are welcome to come early at 8:00am ET to give extra time for set up."
contactUs: "/about/#contact-us"

# 
# Slack Invite URL
# Also change this in the links section below
#
slackInviteUrl: https://join.slack.com/t/bsidesnyc/shared_invite/zt-3ehtljcnl-bzDSX_sPOAVwiEPFDg18rA

#-----------------------------------------------
# Footer
#-----------------------------------------------
socialLinks:
  - icon: twitter
    link: https://twitter.com/bsidesnyc
  - icon: linkedin
    link: https://www.linkedin.com/company/bsidesnyc

footerBlocks:
  - title: Links
    links:
      - text: BSidesNYC
        permalink: /
      - text: Security BSides
        link: http://www.securitybsides.com
  - title: Contacts
    links:
      - text: Mailing List
        permalink: /about/#contact-us
      - text: Join our Slack
        link: https://join.slack.com/t/bsidesnyc/shared_invite/zt-3ehtljcnl-bzDSX_sPOAVwiEPFDg18rA
      - text: "bsides(at)bsidesnyc.org"
        link: mailto:bsides@bsidesnyc.org
      - text: Volunteer
        permalink: /about/#volunteers
  - title: Policies
    links:
      - text: "CoC & Anti-Harassment"
        permalink: /policies/
  - title: Press
    links:
      - text: Press Passes
        permalink: /about/#contact-us
      - text: Logo Kit 
        permalink: /img/bsidesnyc_logo_original.zip

#-----------------------------------------------
# Head
#-----------------------------------------------
metaKeywords: "bsides, security, bsidesnyc, conference, nyc"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

#-----------------------------------------------
# Navigation
#-----------------------------------------------
navigationLinks:
 - {permalink: "/venue/", text: "Venue"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/villages/", text: "Villages"}
 - {permalink: "/ctf/", text: "CTF"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/video/", text: "Video"}
 - {permalink: "/registration/", text: "Registration"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/cfp/", text: "CFP"}
 - {permalink: "/about/", text: "About"}
bottomNavigationLinks:
rightNavigationButtons:

################################################################################################
# Block Data
################################################################################################

#-----------------------------------------------
# About
#-----------------------------------------------
aboutTitle: "About BSidesNYC"
aboutCaption: "BSidesNYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community and we truly strive to keep information free."
aboutBlock:
  - {title: "Conference", image: "conference.jpg", text: "Three technical tracks based on the themes of Red Teams, Blue Teams, and Other content. Plus an Entreprenuer track for the bold!" }
  - {title: "Villages", image: "villages.jpg", text: "Discover different realms of security, hacking, and local community-driven organizations." }
  - {title: "Capture The Flag", image: "ctf.jpg", text: "Multiple CTFs with varying levels of technical depth." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1000", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "45", specialCharacter: "+", info: "hours", detail: "of security content"}
 - {count: "58", specialCharacter: "+", info: "speakers", detail: "from across the world"}
 - {count: "5", specialCharacter: "", info: "parallel tracks", detail: "plus villages"}

#-----------------------------------------------
# CFP Block
#-----------------------------------------------
cfpTitle: "Call For Papers"
cfpBoardTitle: "CFP Board"
cfpUrl: "https://docs.google.com/forms/d/e/1FAIpQLSes8dIfojKqXatyC6lNug41d_jsnio0LdIZRlFWms9sbWiUxw/viewform?usp=sf_link"
cfpOpenDate: "April 16, 2025"
cfpCloseDate: "July 18, 2025"
cfpAcceptanceDate: "July 18, 2025"
cfpDuration: "CFP submissions will be accepted from"
cfpAcceptance: "Speaker acceptance notices will start being sent out on"
cfpProcessReviewText: ["Our current conference timeline allocates ~3 months for our CFP to be open for submissions.",

"After our CFP has been closed on July 19, 2025, our CFP review board has ~1 week to look over and score all submissions.",

"Based on the ratings from our CFP review board, the submissions with the highest score are put into our first round of acceptance notices, which start on July 28, 2025.",

"We allow ~1 week for these submitters to respond. <i>If we can not get a hold of, or hear back from, said submitter(s) then we move down our acceptance list</i>. Additionally, circumstatnces may arrise which prevent a submitter from being able or willing to present at our conference. If this occurs, we must once again continue down the acceptance list.",

"This is usually resolved within a week or two, but as you can imagine, we can not send out rejection notices until we have enough talks to fill our schedule.", "Once we have enough acceptances, we will send out notices to those who did not make the final cut, probably starting August 5, 2025. Depending on the volume of CFP submissions, we may not be able to provide personal feedback for each CFP submission."]
cfpProcessAcceptedText: ["Acceptance notice go out over a month ahead of the conference so you can schedule any necessary travel arrangements. <b>If your attendance requires any visa paperwork, please let us know ahead of time</b>.",

"Additionally, we will be posting the speaker list and talk abstracts so please let us know if anything has changed (title, abstract etc.) A.S.A.P.",

"As always, if you would like to have someone come to the conference with you, please just send us their information so we can register them."]

#-----------------------------------------------
# Villages
# also see _data/villages.yml
#-----------------------------------------------
villagesAboutTitle: "About Villages"
villagesTitle: "BSidesNYC 2023 Villages"
villagesUrl: "/villages/"

#-----------------------------------------------
# Event Intro
#-----------------------------------------------
eventImage: "nyc_skyline.jpg"
eventTitle: "BSidesNYC"
eventDate: "18 October 2025"
eventInfo: "The next BSidesNYC will take place in 18 October 2025. To stay updated on volunteer opportunities, and other news, follow us on Twitter <a href=\"https://twitter.com/bsidesnyc\" target=\"_blank\">@BSidesNYC</a> and sign up for the mailing list."
eventButtons:
 - {permalink: "/sponsors/", text: "Become a sponsor", id: "sponsors"}

#-----------------------------------------------
# Location Block
#-----------------------------------------------
locationBlockTitle: "Location"
eventLocationName: "Digital Forensics and Cybersecurity Program @ John Jay College of Criminal Justice"
eventStreetAddress: "524 W 59th St."
eventAddressLocality: "New York"
eventAddressLocalityRegion: "NY"
eventPostalCode: "10019"
eventAddressCountry: "USA"
eventNavigationLink: https://goo.gl/maps/7vwHt4ARqjr
eventStartTime: "2025-10-18T08:00"
eventDoorTime: "09:00"
eventEndTime: "2025-10-18T17:00"
eventPlaceCoordinates: "4087709863, -73.9899653"
mapCenterCoordinates: "40.7709863, -73.9899653"
mapMobileCenterCoordinates: "40.7709863, -73.9899653"

#-----------------------------------------------
# Logistics | Directions
#-----------------------------------------------
directionsTitle: #"Find your way here"
directionsDistance: "Distance"
directionsDriving: "DRIVING"
directionsWalking: "WALKING"
directionsBicycling: "BICYCLING"
directionsTransit: "TRANSIT"
directionsFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.7709863, -73.9899653"
logisticsMapMobileCenterCoordinates: "40.7709863, -73.9899653"
logisticsMapAutoDirections: false

# Logistics Direction Details
directionDetailsImage: "columbus_circle.jpg"
directionDetailsTitle: "Getting Here"
directionDetailsCards:
 - {title: "Airports", information: 'The conference is easily accessible from the <b>JFK</b>, <b>LGA</b>, or <b>EWR</b> airports via public transportation (subway, bus, taxi) or ride-sharing services (uber, lyft etc.)'}
 - {title: "Public Transit", information: "The closest subway station is <b>59 St. - Columbus Circle</b> (A,B,C & D lines). From this stop, it is less than a .5 mile walk."}
 - {title: "Hotels", information: "<a href='https://www.marriott.com/en-us/hotels/nycft-fairfield-inn-and-suites-new-york-manhattan-central-park/overview/'>Fairfield Inn & Suites New York Manhattan/Central Park</a> is right next door."}

#-----------------------------------------------
# Sponsors
#-----------------------------------------------
sponsorsUrl: "/sponsors/"
sponsorshipKitUrl: "/assets/BSidesNYC-0x05-Sponsorship-Prospectus.pdf"

#-----------------------------------------------
# Subscribe
#-----------------------------------------------
subscribeTitle: "Subscribe for updates"
subscribeInfo: "^^^ Please ignore this message above from our mailing list provider. We use the free edition, so this get embedded.<p>We'll only use your email for BSidesNYC announcements. We respect privacy, and don't provide anyone (including sponsors) with this type of information."

#-----------------------------------------------
# Registration | Tickets
#-----------------------------------------------
# If registrationOpen is true, the registration_open content will be shown if:
#   - its after registrationOpenDate; or 
#   - registrationOpenDate is null
#
# if registrationOpen is false, only the registration_closed content will be shown
#
registrationOpen: True
registrationOpenDate: "2025-09-15T20:00:00-04:00"
registrationLink: https://www.ticketleap.events/tickets/bsidesnyc/bsidesnyc-0x05

#-----------------------------------------------
# Venue
#-----------------------------------------------
venueTitle: John Jay College of Criminal Justice
venueAddress: 524 W. 59th Street, New York, NY
venueWiFiSSID: John Jay Events
venueWiFiPW: Events@Jay24
venuePhotosPrimary: atrium.jpg
venuePhotosSecondary:
  - 240.jpg
  - L615.jpg
  - L763.jpg
venueMapsIntro: "Tracks are split across multiple floors. You'll enter and register on the Ground floor where the Red Track (L.63), Keynote (L.63), and Entrepreneur Track (L.61) are. Go down via stairs or elevator to Lower Level (L2) for the Blue Track (L2.84) and Other Track (L2.85). Go up via elevator to the 6th Floor for the Villages (Moot Court) and to the 9th for CTF."
venueFloorMaps:
  - name: Ground Floor (L)
    divId: map-l
    image: bsidesnyc-johnjay-ground-floor.png
  - name: Lower Level (L2)
    image: bsidesnyc-johnjay-L2.png
    divId: map-l2
  - name: 6th Floor
    image: bsidesnyc-johnjay-6th.png
    divId: map-6
  - name: 9th Floor
    image: bsidesnyc-johnjay-9th.png
    divId: map-9

#-----------------------------------------------
# Volunteers
#-----------------------------------------------
volunteersTitle: "Want to Volunteer?"
volunteersSubscribeTitle: "Join the Team"

#-----------------------------------------------
# CTF 
#-----------------------------------------------
ctfHeader: Game On! 
ctfHeaderMessage: We are so excited to offer multiple Capture The Flag (CTF) competitions. Play one or play them all! All CTFs require a laptop and have both offensive and defensive challenges.
ctfHeaderMessageFloor: Visit the CTF space in the Cafeteria/Student Dining Hall (second floor, room 2.64)
# TODO: This year we have 4 CTFs! Time to move it out of the _config.yml and into its own _data/ctf.yml 
ctfs:
  #
  # CTFd 
  #
  - logo: ctfd.svg
    header: Play Whenever
    features:
      - Jeopardy-Style CTF
      - Reverse engineering, vulnerable web applications, and more
      - Play all day or casually pick up a challenge
      - Individual or team-based
      - Compare your progress against others on leaderboard
    registration: # No more than 2 registration buttons
      - url: https://ctfd.io
        disabled: true 
        title: Register In Person 
    registrationMessage: Registration will be in-person at the CTF space the day of event
    url: https://ctfd.io/#bsidesnyc
  #
  # Pros Vs Joes
  #
  - logo: PvJlogo.png 
    header: Full Day Event
    features:
      - Register before BSidesNYC to participate
      - Offensive vs Defensive Style CTF
      - Team based activities
      - "\"Joes\" learn and face challenges"
      - "\"Pros\" flex their skills and help the Joes"
    registration: # No more than 2 registration buttons
      - url: https://docs.google.com/forms/d/e/1FAIpQLSdp4dASdkh1i1gOULIpXl28ZDXte2HknSHVXAsMWLWxe5V6bw/viewform
        disabled: false
        title: Pro Registration 
      - url: https://docs.google.com/forms/d/e/1FAIpQLSc2-k27UNqObt19-0tJvacWNHHYev-fKxuUk7px4gHIPhEswA/viewform
        disabled: false
        title: Joe Registration
    registrationMessage: 
    url: http://prosversusjoes.net/#bsidesnyc
  #
  # Red Team Village CTF 
  #
  - logo: rtv.png 
    header: Play Whenever
    features:
      - Jeopardy-Style CTF
      - AI, Web, Pwnables, wide variety of challenges
      - Play all day or just try one!
      - Individual or team-based
      - Leaderboard with Swag & workshop prizes for winners
    registration: # No more than 2 registration buttons
      - url: https://threatsims.com/user/events/904259c3-c646-4adc-85b1-91c719b52384
        disabled: false
        title: Register Now 
    registrationMessage: 
    url: https://redteamvillage.io/#bsidesnyc
  #
  # AI Security Village
  #
  - logo: aisecurityvillage.png 
    header: Play Whenever
    features:
      - Jeopardy-Style CTF
      - AI-related challenges
      - Play all day or casually pick up a challenge
      - Individual Participants
      - Leaderboard with cash prizes for 1st and 2nd place
      - Registration in person at the AI Security Village
    registration: # No more than 2 registration buttons
      - url: https://align-sec.org/events/2025-bsidesnyc
        disabled: true 
        title: Register In Person 
    registrationMessage: 
    url: https://align-sec.org/events/2025-bsidesnyc

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "bsidesnyc"
twitterFeed: ""

#-----------------------------------------------
# Sessionize Links
#-----------------------------------------------
sessionizeJsonSpeakerList: https://sessionize.com/api/v2/sfqscpbj/view/Speakers
sessionizeJsonSessionList: https://sessionize.com/api/v2/sfqscpbj/view/Sessions
sessionizeJsonAllData: https://sessionize.com/api/v2/sfqscpbj/view/All
# Important: Select "Use UTC timezone for schedule" for the schedule grid in sessionize
sessionizeJsonScheduleGrid: https://sessionize.com/api/v2/sfqscpbj/view/GridSmart

